[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rcic-website"
authors = [{name='rcic', email='rcic-git-notifications@uci.edu'}]

dynamic = ["version", "description"]
